server:
  port: 8082
spring:
  application:
    name: orderMgmtService
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka
        instance:
        preferIpAddress: true