server:
  port: 8081
spring:
  application:
    name: restaurant-mgmt-service
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka
        instance:
        preferIpAddress: true